# Generated by Django 3.2.5 on 2022-05-05 10:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 5, 10, 14, 14, 844431, tzinfo=utc)),
        ),
    ]
